version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./uploads:/root/uploads  # only mount uploads
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=bharat_seva_space
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Online@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
