version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Online@123
      - DB_NAME=bharat_seva_space
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRY=24h
      - PORT=8080
      - ENV=production
      - UPLOAD_PATH=./uploads
      - MAX_FILE_SIZE=10485760
    depends_on:
      - postgres
    volumes:
      - ./uploads:/root/uploads
      - ./config.env:/root/config.env

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=bharat_seva_space
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Online@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 